SELECT
    str_split(HREF, '/')[-3]::INTEGER AS ID_TIME,
    str_split(HREF, '/')[-1]::INTEGER + 1 AS ID_TEMPORADA,
    'BRASILEIRÃO SERIE A' AS NOME_CAMPEONATO,
    POSICAO AS POSICAO_FINAL,
    upper(CLUBE) AS CLUBE,
    JOGOS,
    V AS VITORIAS,
    E AS EMPATES,
    D AS DERROTAS,
    str_split(GOLS, ':')[1]::INTEGER AS GOLS_PRO,
	str_split(GOLS, ':')[2]::INTEGER AS GOLS_CONTRA,
    SG AS SALDO_DE_GOLS,
    PTS AS PONTOS,
    upper(CLASSIFICACAO) AS CLASSIFICACAO,
    ESCUDO AS IMG_ESCUDO,
    upper(STATUS_TEMPORADA_PASSADA) AS STATUS_TEMPORADA_PASSADA,
    upper(TITULO_TEMPORADA_PASSADA) AS TITULO_TEMPORADA_PASSADA
FROM
    {{ ref("tabela_classificacao_serie_a") }}