SELECT 
	ID_TIME,
	ID_TEMPORADA,
	NOME_CAMPEONATO,
	ID_RODADA,
	ID_JOGO,
	DIA,
	DATA_HORA_JOGO,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN TIME_CASA
		WHEN ID_TIME = ID_TIME_VISITANTE THEN TIME_VISITANTE
	END NOME_TIME,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN TIME_VISITANTE
		WHEN ID_TIME = ID_TIME_VISITANTE THEN TIME_CASA
	END NOME_ADVERSARIO,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN ID_TIME_VISITANTE
		WHEN ID_TIME = ID_TIME_VISITANTE THEN ID_TIME_CASA
	END ID_TIME_ADVERSARIO,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN 1
		WHEN ID_TIME = ID_TIME_VISITANTE THEN 0
	END FLG_JOGO_EM_CASA,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN GOLS_TIME_CASA
		WHEN ID_TIME = ID_TIME_VISITANTE THEN GOLS_TIME_VISITANTE
	END GOLS_PRO,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN GOLS_TIME_VISITANTE
		WHEN ID_TIME = ID_TIME_VISITANTE THEN GOLS_TIME_CASA
	END GOLS_CONTRA,
	SUM(GOLS_PRO) OVER (PARTITION BY ID_TIME, ID_TEMPORADA, NOME_CAMPEONATO ORDER BY DATA_HORA_JOGO ASC) AS GOLS_PRO_ACUMULADOS,
	SUM(GOLS_CONTRA) OVER (PARTITION BY ID_TIME, ID_TEMPORADA, NOME_CAMPEONATO ORDER BY DATA_HORA_JOGO ASC) AS GOLS_CONTRA_ACUMULADOS,
	CASE
		WHEN GOLS_PRO > GOLS_CONTRA THEN 3
		WHEN GOLS_PRO = GOLS_CONTRA THEN 1
		WHEN GOLS_PRO < GOLS_CONTRA THEN 0
	END AS PONTOS,
	SUM(PONTOS) OVER (PARTITION BY ID_TIME, ID_TEMPORADA, NOME_CAMPEONATO ORDER BY DATA_HORA_JOGO ASC) AS PONTOS_ACUMULADOS,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN POSICAO_TIME_CASA_NA_RODADA
		WHEN ID_TIME = ID_TIME_VISITANTE THEN POSICAO_TIME_VISITANTE_NA_RODADA
	END POSICAO_TIME_NA_RODADA,
	CASE
		WHEN ID_TIME = ID_TIME_CASA THEN POSICAO_TIME_VISITANTE_NA_RODADA
		WHEN ID_TIME = ID_TIME_VISITANTE THEN POSICAO_TIME_CASA_NA_RODADA
	END POSICAO_ADVERSARIO_NA_RODADA,
	SISTEMA_DE_JOGO,
	TREINADOR,
	ID_TREINADOR,
	PUBLICO
FROM 
    {{ ref("vw_tabela_jogo_a_jogo") }}